### ISSUE TITLE
Please make installation easier!

### ISSUE THREAD

**Issue by upendra-k14** [SuyashLakhotia/CodeBot#3]
Hello @chaitjo 
Since this app is targeted for beginners, the installation should be done using single command. You can't expect beginners to go through long list of instructions for installing and setting up different modules. :)

**Comment by SuyashLakhotia** [comment]
@upendra-k14 Hey, the installation in `README.md` is meant for contributors to the project and not the end users. Once we have `v1.0` of the project ready, we'll deploy the web app online for users!

**Comment by chaitjo** [comment]
Awsomesauce
